[{
  "history_id" : "p6977t6u1vo",
  "history_input" : "\n\n\n# Suppress warnings\nimport warnings\nwarnings.simplefilter('ignore')\nwarnings.filterwarnings('ignore')\n\n# Direct access\nimport earthaccess \nfrom pprint import pprint\nimport xarray as xr\n\n# Harmony\nimport geopandas as gpd\nimport geoviews as gv\ngv.extension('bokeh', 'matplotlib')\nfrom harmony import BBox, Client, Collection, Request, LinkType\nimport datetime as dt\nimport s3fs",
  "history_output" : "Traceback (most recent call last):\n  File \"/Users/joe/gw-workspace/p6977t6u1vo/earth_data_utils.py\", line 10, in <module>\n    import earthaccess \nModuleNotFoundError: No module named 'earthaccess'\n",
  "history_begin_time" : 1686759148585,
  "history_end_time" : 1686759148955,
  "history_notes" : null,
  "history_process" : "wttkvt",
  "host_id" : "100001",
  "indicator" : "Failed"
},{
  "history_id" : "3l2y4206qef",
  "history_input" : "from earth_data_utils import *\n\nssh_short_name = \"SEA_SURFACE_HEIGHT_ALT_GRIDS_L4_2SATS_5DAY_6THDEG_V_JPL2205\"\n\nresults = earthaccess.search_data(\n    short_name=ssh_short_name,\n    cloud_hosted=True,\n    temporal=(\"2021-07-01\", \"2021-09-30\"),\n)",
  "history_output" : "Traceback (most recent call last):\n  File \"/Users/joe/gw-workspace/3l2y4206qef/search_data.py\", line 1, in <module>\n    from earth_data_utils import *\n  File \"/Users/joe/gw-workspace/3l2y4206qef/earth_data_utils.py\", line 10, in <module>\n    import earthaccess \nModuleNotFoundError: No module named 'earthaccess'\n",
  "history_begin_time" : 1686759150591,
  "history_end_time" : 1686759150744,
  "history_notes" : null,
  "history_process" : "yvo1ds",
  "host_id" : "100001",
  "indicator" : "Failed"
},{
  "history_id" : "74iyqhnh28j",
  "history_input" : "from search_data import *\n\nsst_short_name=\"MUR-JPL-L4-GLOB-v4.1\"\n\nresults = earthaccess.search_data(\n    short_name=ssh_short_name,\n    cloud_hosted=True,\n    temporal=(\"2021-07-01\", \"2021-09-30\"),\n)\n\nauth = earthaccess.login(strategy=\"netrc\", persist=True)\nds = xr.open_mfdataset(earthaccess.open(results))\ngeojson_path = '/home/jovyan/gulf.json'\ngdf = gpd.read_file(geojson_path) #Return a GeoDataFrame object\n\n\nharmony_client = Client()\nsst_short_name=\"MUR-JPL-L4-GLOB-v4.1\"\n\nrequest = Request(\n  collection=Collection(id=sst_short_name),\n  shape=geojson_path,\n  temporal={\n    'start': dt.datetime(2021, 8, 1, 1),\n    'stop': dt.datetime(2021, 8, 1, 2)   \n  },\n)\njob_id = harmony_client.submit(request)\nharmony_client.wait_for_processing(job_id, show_progress=False)\ndata = harmony_client.result_json(job_id)\nresults = harmony_client.result_urls(job_id, link_type=LinkType.s3)\nurls = list(results)\nurl = urls[0]\n",
  "history_output" : "Traceback (most recent call last):\n  File \"/Users/joe/gw-workspace/74iyqhnh28j/earth_access_authenticate.py\", line 1, in <module>\n    from search_data import *\n  File \"/Users/joe/gw-workspace/74iyqhnh28j/search_data.py\", line 1, in <module>\n    from earth_data_utils import *\n  File \"/Users/joe/gw-workspace/74iyqhnh28j/earth_data_utils.py\", line 10, in <module>\n    import earthaccess \nModuleNotFoundError: No module named 'earthaccess'\n",
  "history_begin_time" : 1686759152006,
  "history_end_time" : 1686759152136,
  "history_notes" : null,
  "history_process" : "cgvhiy",
  "host_id" : "100001",
  "indicator" : "Failed"
},{
  "history_id" : "uu96597mlq0",
  "history_input" : "# Suppress warnings\nimport os\nimport warnings\nwarnings.simplefilter('ignore')\nwarnings.filterwarnings('ignore')\n\n# Direct access\nimport earthaccess \nfrom pprint import pprint\nimport xarray as xr\n\n# Harmony\nimport geopandas as gpd\nimport geoviews as gv\ngv.extension('bokeh', 'matplotlib')\nfrom harmony import BBox, Client, Collection, Request, LinkType\nimport datetime as dt\nimport s3fs\nimport matplotlib.pyplot as plt\nfrom earth_access_authenticate import *\n\ncreds = harmony_client.aws_credentials()\ns3_fs = s3fs.S3FileSystem(\n  key=creds['aws_access_key_id'],\n  secret=creds['aws_secret_access_key'],\n  token=creds['aws_session_token'],\n  client_kwargs={'region_name':'us-west-2'},\n)\nf = s3_fs.open(url, mode='rb')\nds = xr.open_dataset(f)\nds.analysed_sst.plot()\nhome_dir = os.path.expanduser('~')\nplt.savefig(os.path.join(home_dir, 'plot2.png'))",
  "history_output" : "Traceback (most recent call last):\n  File \"/Users/joe/gw-workspace/uu96597mlq0/s3_file_storage.py\", line 8, in <module>\n    import earthaccess \nModuleNotFoundError: No module named 'earthaccess'\n",
  "history_begin_time" : 1686759153783,
  "history_end_time" : 1686759153919,
  "history_notes" : null,
  "history_process" : "1b4ko0",
  "host_id" : "100001",
  "indicator" : "Failed"
}]
