[{
  "history_id" : "RstYQnVPwfbH",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-02\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_sst.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nwith get_dataset(search_and_get_sst()) as ds:\n  subset = ds[\"analysed_sst\"].sel(lat=slice(37, 47), \n                                lon=slice(-70,-50)).std('time')\n  plot_subset(subset)\n\n",
  "history_output" : "WARNING:param.notebook_extension: Holoviews bokeh extension could not be imported, it raised the following exception: ValueError('ClassSelector parameter None value must be an instance of (function, tuple), not <function size at 0x7f97582fb670>.')\nWARNING:param.notebook_extension: bokeh backend hook <function _load_bokeh at 0x7f9768d89b80> failed with following exception: ClassSelector parameter None value must be an instance of (function, tuple), not <function size at 0x7f97582fb670>.\nYou're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 2\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 2 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 2/2 [00:00<00:00, 874.18it/s]\nPROCESSING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nPROCESSING TASKS | :  50%|█████     | 1/2 [00:01<00:01,  1.20s/it]\nPROCESSING TASKS | : 100%|██████████| 2/2 [00:01<00:00,  1.67it/s]\nCOLLECTING RESULTS | :   0%|          | 0/2 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 2/2 [00:00<00:00, 30283.78it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_sst.png\n",
  "history_begin_time" : 1689697460264,
  "history_end_time" : 1689697703257,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Done"
},{
  "history_id" : "0snzg8m33qw",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-02\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_sst.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nwith get_dataset(search_and_get_sst()) as ds:\n  subset = ds[\"analysed_sst\"].sel(lat=slice(37, 47), \n                                lon=slice(-70,-50)).std('time')\n  plot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 2\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 2 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 2/2 [00:00<00:00, 2281.37it/s]\nPROCESSING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nPROCESSING TASKS | :  50%|█████     | 1/2 [00:00<00:00,  1.35it/s]\nPROCESSING TASKS | : 100%|██████████| 2/2 [00:00<00:00,  2.52it/s]\nCOLLECTING RESULTS | :   0%|          | 0/2 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 2/2 [00:00<00:00, 17403.75it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_sst.png\n",
  "history_begin_time" : 1687374951105,
  "history_end_time" : 1687374982667,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : "100001",
  "indicator" : "Done"
},{
  "history_id" : "orznud2v2ugsyqfjlj",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-02\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_sst.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nwith get_dataset(search_and_get_sst()) as ds:\n  subset = ds[\"analysed_sst\"].sel(lat=slice(37, 47), \n                                lon=slice(-70,-50)).std('time')\n  plot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 2\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 2 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 2/2 [00:00<00:00, 2267.80it/s]\nPROCESSING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nPROCESSING TASKS | :  50%|█████     | 1/2 [00:00<00:00,  1.53it/s]\nPROCESSING TASKS | : 100%|██████████| 2/2 [00:00<00:00,  2.71it/s]\nCOLLECTING RESULTS | :   0%|          | 0/2 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 2/2 [00:00<00:00, 16131.94it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_sst.png\n",
  "history_begin_time" : 1687333226859,
  "history_end_time" : 1687333260137,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Done"
},{
  "history_id" : "e1ce5zjdm3y",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-02\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_sst.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nwith get_dataset(search_and_get_sst()) as ds:\n  subset = ds[\"analysed_sst\"].sel(lat=slice(37, 47), \n                                lon=slice(-70,-50)).std('time')\n  plot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 2\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 2 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 2/2 [00:00<00:00, 1568.26it/s]\nPROCESSING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nPROCESSING TASKS | :  50%|█████     | 1/2 [00:00<00:00,  1.21it/s]\nPROCESSING TASKS | : 100%|██████████| 2/2 [00:00<00:00,  2.42it/s]\nCOLLECTING RESULTS | :   0%|          | 0/2 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 2/2 [00:00<00:00, 21454.24it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_sst.png\n",
  "history_begin_time" : 1687333075840,
  "history_end_time" : 1687333113137,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : "100001",
  "indicator" : "Done"
},{
  "history_id" : "afz7j3dzavr",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-02\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nwith get_dataset(search_and_get_sst()) as ds:\n  subset = ds[\"analysed_sst\"].sel(lat=slice(37, 47), \n                                lon=slice(-70,-50)).std('time')\n  plot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 2\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 2 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 2/2 [00:00<00:00, 2219.21it/s]\nPROCESSING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nPROCESSING TASKS | :  50%|█████     | 1/2 [00:00<00:00,  1.56it/s]\nPROCESSING TASKS | : 100%|██████████| 2/2 [00:00<00:00,  3.11it/s]\nCOLLECTING RESULTS | :   0%|          | 0/2 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 2/2 [00:00<00:00, 9521.69it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_653798d7-3e88-4a03-9b03-e746fc763432.png\n",
  "history_begin_time" : 1687332825739,
  "history_end_time" : 1687332857617,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : "100001",
  "indicator" : "Done"
},{
  "history_id" : "fk604fwceda",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-02\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_sst.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nwith get_dataset(search_and_get_sst()) as ds:\n  subset = ds[\"analysed_sst\"].sel(lat=slice(27, 37), \n                                lon=slice(-70,-50)).std('time')\n  plot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 2\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 2 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 2/2 [00:00<00:00, 1421.56it/s]\nPROCESSING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nPROCESSING TASKS | :  50%|█████     | 1/2 [00:00<00:00,  1.51it/s]\nPROCESSING TASKS | : 100%|██████████| 2/2 [00:00<00:00,  2.97it/s]\nPROCESSING TASKS | : 100%|██████████| 2/2 [00:00<00:00,  2.59it/s]\nCOLLECTING RESULTS | :   0%|          | 0/2 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 2/2 [00:00<00:00, 22192.08it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_sst.png\n",
  "history_begin_time" : 1687332626691,
  "history_end_time" : 1687332660588,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : "100001",
  "indicator" : "Done"
},{
  "history_id" : "uf7ngwa1cnl",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-02\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_sst.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nwith get_dataset(search_and_get_sst()) as ds:\n  subset = ds[\"analysed_sst\"].sel(lat=slice(27, 37), \n                                lon=slice(-70,-50)).std('time')\n  plot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 2\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 2 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 2/2 [00:00<00:00, 629.96it/s]\nPROCESSING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nPROCESSING TASKS | :  50%|█████     | 1/2 [00:00<00:00,  1.42it/s]\nPROCESSING TASKS | : 100%|██████████| 2/2 [00:00<00:00,  2.62it/s]\nCOLLECTING RESULTS | :   0%|          | 0/2 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 2/2 [00:00<00:00, 30727.50it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_sst.png\n",
  "history_begin_time" : 1687332443479,
  "history_end_time" : 1687332476093,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : "100001",
  "indicator" : "Done"
},{
  "history_id" : "jxyo4sjnw7i4dsvt30",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-02\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nwith get_dataset(search_and_get_sst()) as ds:\n  subset = ds[\"analysed_sst\"].sel(lat=slice(37, 47), \n                                lon=slice(-70,-50)).std('time')\n  plot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 2\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 2 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 2/2 [00:00<00:00, 2303.93it/s]\nPROCESSING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nPROCESSING TASKS | :  50%|█████     | 1/2 [00:00<00:00,  1.16it/s]\nPROCESSING TASKS | : 100%|██████████| 2/2 [00:00<00:00,  2.31it/s]\nCOLLECTING RESULTS | :   0%|          | 0/2 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 2/2 [00:00<00:00, 34663.67it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_1c1fdc06-031c-47bd-918a-b9856564678c.png\n",
  "history_begin_time" : 1687331264443,
  "history_end_time" : 1687331302248,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Done"
},{
  "history_id" : "m3t1sdcsl3k",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-02\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nwith get_dataset(search_and_get_sst()) as ds:\n  subset = ds[\"analysed_sst\"].sel(lat=slice(37, 47), \n                                lon=slice(-70,-50)).std('time')\n  plot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 2\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 2 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 2/2 [00:00<00:00, 1976.11it/s]\nPROCESSING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nPROCESSING TASKS | :  50%|█████     | 1/2 [00:00<00:00,  1.10it/s]\nPROCESSING TASKS | : 100%|██████████| 2/2 [00:00<00:00,  2.19it/s]\nCOLLECTING RESULTS | :   0%|          | 0/2 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 2/2 [00:00<00:00, 31184.42it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_fea247c9-dea7-4e63-9db6-7739693423f9.png\n",
  "history_begin_time" : 1687330978529,
  "history_end_time" : 1687331011363,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : "100001",
  "indicator" : "Done"
},{
  "history_id" : "ohvdmvpfy1m",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-02\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nwith get_dataset(search_and_get_sst()) as ds:\n  subset = ds[\"analysed_sst\"].sel(lat=slice(27, 37), \n                                lon=slice(-70,-50)).std('time')\n  plot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 2\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 2 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 2/2 [00:00<00:00, 2064.13it/s]\nPROCESSING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nPROCESSING TASKS | :  50%|█████     | 1/2 [00:00<00:00,  1.20it/s]\nPROCESSING TASKS | : 100%|██████████| 2/2 [00:00<00:00,  2.41it/s]\nCOLLECTING RESULTS | :   0%|          | 0/2 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 2/2 [00:00<00:00, 29959.31it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_63be6e01-ad21-4f90-b241-cd75713ea023.png\n",
  "history_begin_time" : 1687322107128,
  "history_end_time" : 1687322141058,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : "100001",
  "indicator" : "Done"
},{
  "history_id" : "55ierovrm5x",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-02\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nwith get_dataset(search_and_get_sst()) as ds:\n  subset = ds[\"analysed_sst\"].sel(lat=slice(27, 37), \n                                lon=slice(-70,-50)).std('time')\n  plot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 2\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 2 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 2/2 [00:00<00:00, 665.34it/s]\nPROCESSING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nPROCESSING TASKS | :  50%|█████     | 1/2 [00:00<00:00,  1.19it/s]\nPROCESSING TASKS | : 100%|██████████| 2/2 [00:00<00:00,  2.34it/s]\nCOLLECTING RESULTS | :   0%|          | 0/2 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 2/2 [00:00<00:00, 28244.47it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_a7b93751-c484-4c4a-a14c-08ce467a91c9.png\n",
  "history_begin_time" : 1687321311164,
  "history_end_time" : 1687321346277,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : "100001",
  "indicator" : "Done"
},{
  "history_id" : "EcOKe1e6zRlz",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-02\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nwith get_dataset(search_and_get_sst()) as ds:\n  subset = ds[\"analysed_sst\"].sel(lat=slice(27, 37), \n                                lon=slice(-70,-50)).std('time')\n  plot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 2\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 2 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 2/2 [00:00<00:00, 1809.45it/s]\nPROCESSING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nPROCESSING TASKS | :  50%|█████     | 1/2 [00:00<00:00,  1.42it/s]\nPROCESSING TASKS | : 100%|██████████| 2/2 [00:00<00:00,  2.83it/s]\nCOLLECTING RESULTS | :   0%|          | 0/2 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 2/2 [00:00<00:00, 24036.13it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_145fb998-bfd4-465d-a580-dd4e589ec2b7.png\n",
  "history_begin_time" : 1687321176446,
  "history_end_time" : 1687321210986,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Done"
},{
  "history_id" : "Clldd9m98PAt",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-02\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nds = get_dataset(search_and_get_sst())\nsubset = ds[\"analysed_sst\"].sel(lat=slice(27, 37), \n                                lon=slice(-70,-50)).std('time')\nplot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 2\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 2 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 2/2 [00:00<00:00, 499.89it/s]\nPROCESSING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nPROCESSING TASKS | :  50%|█████     | 1/2 [00:00<00:00,  1.13it/s]\nPROCESSING TASKS | : 100%|██████████| 2/2 [00:00<00:00,  2.25it/s]\nCOLLECTING RESULTS | :   0%|          | 0/2 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 2/2 [00:00<00:00, 23237.14it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_b2ee5a87-6a43-41d9-a366-f1ede6c21f61.png\nException ignored in: <function CachingFileManager.__del__ at 0x7f97740ef280>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 585, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7f9774658ca0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 585, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7f97740ef280>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 585, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7f9774658ca0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 585, in close\nTypeError: bad operand type for unary ~: 'NoneType'\n",
  "history_begin_time" : 1687320933330,
  "history_end_time" : 1687320969377,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Done"
},{
  "history_id" : "sAZF2bohiT4g",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-02\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nds = get_dataset(search_and_get_sst())\nsubset = ds[\"analysed_sst\"].sel(lat=slice(27, 37), \n                                lon=slice(-70,-50)).std('time')\nplot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 2\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 2 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 2/2 [00:00<00:00, 1127.35it/s]\nPROCESSING TASKS | :   0%|          | 0/2 [00:00<?, ?it/s]\nPROCESSING TASKS | :  50%|█████     | 1/2 [00:00<00:00,  1.38it/s]\nPROCESSING TASKS | : 100%|██████████| 2/2 [00:00<00:00,  2.76it/s]\nCOLLECTING RESULTS | :   0%|          | 0/2 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 2/2 [00:00<00:00, 28630.06it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_6d76b1b4-8ce5-435a-a242-4246bfe70a7e.png\nException ignored in: <function CachingFileManager.__del__ at 0x7fdef16e7280>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fdee2a92dc0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fdef16e7280>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fdee2a92dc0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\n",
  "history_begin_time" : 1687320658009,
  "history_end_time" : 1687320689683,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Done"
},{
  "history_id" : "muhcxxqhzna",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-04\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nds = get_dataset(search_and_get_sst())\nsubset = ds[\"analysed_sst\"].sel(lat=slice(27, 37), \n                                lon=slice(-70,-50)).std('time')\nplot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 4\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-03T21:00:00.000Z', 'BeginningDateTime': '2021-07-02T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210703090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-04T21:00:00.000Z', 'BeginningDateTime': '2021-07-03T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210704090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 4 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 4/4 [00:00<00:00, 786.48it/s]\nPROCESSING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nPROCESSING TASKS | :  25%|██▌       | 1/4 [00:00<00:02,  1.39it/s]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:00<00:00,  5.40it/s]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:00<00:00,  4.44it/s]\nCOLLECTING RESULTS | :   0%|          | 0/4 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 4/4 [00:00<00:00, 44384.17it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_7ca5eeb9-e6c2-4650-b9ae-e7b181534b9e.png\nException ignored in: <function CachingFileManager.__del__ at 0x7f988af371f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7f988b04ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7f988af371f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7f988b04ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7f988af371f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7f988b04ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7f988af371f0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7f988b04ad30>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\n",
  "history_begin_time" : 1687320524419,
  "history_end_time" : 1687320576507,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : "100001",
  "indicator" : "Done"
},{
  "history_id" : "5c4g1wdrzme",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-04\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nds = get_dataset(search_and_get_sst())\nsubset = ds[\"analysed_sst\"].sel(lat=slice(27, 37), \n                                lon=slice(-70,-50)).std('time')\nplot_subset(subset)\n\n",
  "history_output" : "Running",
  "history_begin_time" : 1687320443881,
  "history_end_time" : 1687320455184,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : "100001",
  "indicator" : "Done"
},{
  "history_id" : "V4V7YE0Q20Qd",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-04\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nds = get_dataset(search_and_get_sst())\nsubset = ds[\"analysed_sst\"].sel(lat=slice(27, 37), \n                                lon=slice(-70,-50)).std('time')\nplot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 4\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-03T21:00:00.000Z', 'BeginningDateTime': '2021-07-02T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210703090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-04T21:00:00.000Z', 'BeginningDateTime': '2021-07-03T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210704090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 4 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 4/4 [00:00<00:00, 1107.70it/s]\nPROCESSING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nPROCESSING TASKS | :  25%|██▌       | 1/4 [00:00<00:02,  1.14it/s]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:00<00:00,  4.57it/s]\nCOLLECTING RESULTS | :   0%|          | 0/4 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 4/4 [00:00<00:00, 33621.68it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_634c264f-2dbf-40a7-b3e5-22dc37cd2fa0.png\nException ignored in: <function CachingFileManager.__del__ at 0x7fa4645ff280>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fa464c59dc0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fa4645ff280>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fa464c59dc0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fa4645ff280>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fa464c59dc0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7fa4645ff280>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7fa464c59dc0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\n",
  "history_begin_time" : 1687320326906,
  "history_end_time" : 1687320380076,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Done"
},{
  "history_id" : "gH0Y1ntFvvJQ",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-04\"),\n  )\n  print(\"found results: \", results)\n  return results\n\ndef plot_subset(ds_subset):\n  ds_subset.plot(figsize=(12,6), x='lon', y='lat')\n  home_dir = os.path.expanduser('~')\n  \n  file_name = f\"geoweaver_plot_{str(uuid.uuid4())}.png\"\n  save_file_path = os.path.join(home_dir, file_name)\n  plt.savefig(save_file_path)\n  print(f\"new figure is saved to {save_file_path}\")\n\nds = get_dataset(search_and_get_sst())\nsubset = ds[\"analysed_sst\"].sel(lat=slice(27, 37), \n                                lon=slice(-70,-50)).std('time')\nplot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 4\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-03T21:00:00.000Z', 'BeginningDateTime': '2021-07-02T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210703090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-04T21:00:00.000Z', 'BeginningDateTime': '2021-07-03T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210704090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 4 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 4/4 [00:00<00:00, 1113.51it/s]\nPROCESSING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nPROCESSING TASKS | :  25%|██▌       | 1/4 [00:00<00:02,  1.17it/s]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:00<00:00,  5.18it/s]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:00<00:00,  4.12it/s]\nCOLLECTING RESULTS | :   0%|          | 0/4 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 4/4 [00:00<00:00, 12455.25it/s]\nnew figure is saved to /Users/joe/geoweaver_plot_17f2f743-9ad3-428f-a74b-3229f5e84d39.png\nException ignored in: <function CachingFileManager.__del__ at 0x7facb4aff280>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7facb511adc0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7facb4aff280>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7facb511adc0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7facb4aff280>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7facb511adc0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7facb4aff280>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7facb511adc0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\n",
  "history_begin_time" : 1687320061589,
  "history_end_time" : 1687320117329,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Done"
},{
  "history_id" : "bc8wLVHggQC2",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-04\"),\n  )\n  print(\"found results: \", results)\n  return results\n\nds = get_dataset(search_and_get_sst())\nsubset = ds[\"analysed_sst\"].sel(lat=slice(27, 37), \n                                lon=slice(-70,-50)).std('time')\nplot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 4\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-03T21:00:00.000Z', 'BeginningDateTime': '2021-07-02T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210703090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-04T21:00:00.000Z', 'BeginningDateTime': '2021-07-03T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210704090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 4 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 4/4 [00:00<00:00, 716.21it/s]\nPROCESSING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nPROCESSING TASKS | :  25%|██▌       | 1/4 [00:00<00:02,  1.39it/s]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:00<00:00,  6.07it/s]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:00<00:00,  4.85it/s]\nCOLLECTING RESULTS | :   0%|          | 0/4 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 4/4 [00:00<00:00, 58661.59it/s]\nTraceback (most recent call last):\n  File \"/Users/joe/gw-workspace/bc8wLVHggQC2/retrieve_sst.py\", line 16, in <module>\n    plot_subset(subset)\n  File \"/Users/joe/gw-workspace/bc8wLVHggQC2/earth_data_utils.py\", line 65, in plot_subset\n    ds_subset.plot(figsize=(12,6), x='Longitude', y='Latitude')\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/plot/plot.py\", line 862, in __call__\n    return plot(self._da, **kwargs)\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/plot/plot.py\", line 330, in plot\n    return plotfunc(darray, **kwargs)\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/plot/plot.py\", line 1132, in newplotfunc\n    xlab, ylab = _infer_xy_labels(\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/plot/utils.py\", line 399, in _infer_xy_labels\n    _assert_valid_xy(darray, x, \"x\")\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/plot/utils.py\", line 425, in _assert_valid_xy\n    raise ValueError(f\"{name} must be one of None, '{valid_xy_str}'\")\nValueError: x must be one of None, 'lat', 'lon'\nException ignored in: <function CachingFileManager.__del__ at 0x7f7db0386310>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7f7dc4aa2e50>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7f7db0386310>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7f7dc4aa2e50>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7f7db0386310>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7f7dc4aa2e50>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7f7db0386310>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7f7dc4aa2e50>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\n",
  "history_begin_time" : 1687319743750,
  "history_end_time" : 1687319794311,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Failed"
},{
  "history_id" : "fFuSBuGyhfUh",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-04\"),\n  )\n  print(\"found results: \", results)\n  return results\n\nds = get_dataset(search_and_get_sst())\nsubset = ds[\"analysed_sst\"].sel(lat=slice(-90, 90), \n                                lon=slice(-180,180)).std('time')\nplot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 4\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-03T21:00:00.000Z', 'BeginningDateTime': '2021-07-02T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210703090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-04T21:00:00.000Z', 'BeginningDateTime': '2021-07-03T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210704090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 4 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 4/4 [00:00<00:00, 1006.25it/s]\nPROCESSING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nPROCESSING TASKS | :  25%|██▌       | 1/4 [00:00<00:02,  1.38it/s]\nPROCESSING TASKS | :  75%|███████▌  | 3/4 [00:00<00:00,  4.15it/s]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:01<00:00,  3.75it/s]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:01<00:00,  3.38it/s]\nCOLLECTING RESULTS | :   0%|          | 0/4 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 4/4 [00:00<00:00, 55553.70it/s]\n",
  "history_begin_time" : 1687319066103,
  "history_end_time" : 1687319739992,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Done"
},{
  "history_id" : "Mt9qs1sz3ypu",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-04\"),\n  )\n  print(\"found results: \", results)\n  return results\n\nds = get_dataset(search_and_get_sst())\nsubset = ds[\"analysed_sst\"].sel(lat=slice(-90, 90), \n                                lon=slice(-180,180))\n\t\t\t\t\t\t\t.std('time')\nplot_subset(subset)\n\n",
  "history_output" : "  File \"/Users/joe/gw-workspace/Mt9qs1sz3ypu/retrieve_sst.py\", line 16\n    .std('time')\nIndentationError: unexpected indent\n",
  "history_begin_time" : 1687319053505,
  "history_end_time" : 1687319053553,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Failed"
},{
  "history_id" : "g5wgNPIMKvt6",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-04\"),\n  )\n  print(\"found results: \", results)\n  return results\n\nds = get_dataset(search_and_get_sst())\nsubset = ds[\"analysed_sst\"].sel(lat=slice(-90, 90), \n                                lon=slice(-180,180))\n\t\t\t\t\t\t   .std('time')\nplot_subset(subset)\n\n",
  "history_output" : "  File \"/Users/joe/gw-workspace/g5wgNPIMKvt6/retrieve_sst.py\", line 16\n    .std('time')\nIndentationError: unexpected indent\n",
  "history_begin_time" : 1687319034668,
  "history_end_time" : 1687319034724,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Failed"
},{
  "history_id" : "R1pmcdWqLp6V",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-04\"),\n  )\n  print(\"found results: \", results)\n  return results\n\nds = get_dataset(search_and_get_sst())\nsubset = ds[\"analysed_sst\"].sel(lat=slice(-90, 90), \n                                lon=slice(-180,180))\nplot_subset(subset)\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 4\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-03T21:00:00.000Z', 'BeginningDateTime': '2021-07-02T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210703090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-04T21:00:00.000Z', 'BeginningDateTime': '2021-07-03T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210704090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 4 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 4/4 [00:00<00:00, 1061.85it/s]\nPROCESSING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nPROCESSING TASKS | :  25%|██▌       | 1/4 [00:00<00:02,  1.18it/s]\nPROCESSING TASKS | :  75%|███████▌  | 3/4 [00:00<00:00,  3.85it/s]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:01<00:00,  3.65it/s]\nCOLLECTING RESULTS | :   0%|          | 0/4 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 4/4 [00:00<00:00, 54827.50it/s]\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/common.py\", line 189, in _get_axis_num\n    return self.dims.index(dim)\nValueError: tuple.index(x): x not in tuple\nDuring handling of the above exception, another exception occurred:\nTraceback (most recent call last):\n  File \"/Users/joe/gw-workspace/R1pmcdWqLp6V/retrieve_sst.py\", line 16, in <module>\n    plot_subset(subset)\n  File \"/Users/joe/gw-workspace/R1pmcdWqLp6V/earth_data_utils.py\", line 65, in plot_subset\n    ds_subset.std('Time').plot(figsize=(12,6), x='Longitude', y='Latitude')\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/common.py\", line 63, in wrapped_func\n    return self.reduce(func, dim, axis, skipna=skipna, **kwargs)\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/dataarray.py\", line 2693, in reduce\n    var = self.variable.reduce(func, dim, axis, keep_attrs, keepdims, **kwargs)\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/variable.py\", line 1802, in reduce\n    axis = self.get_axis_num(dim)\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/common.py\", line 185, in get_axis_num\n    return self._get_axis_num(dim)\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/common.py\", line 191, in _get_axis_num\n    raise ValueError(f\"{dim!r} not found in array dimensions {self.dims!r}\")\nValueError: 'Time' not found in array dimensions ('time', 'lat', 'lon')\nException ignored in: <function CachingFileManager.__del__ at 0x7f92f32563a0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7f92ea91aee0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7f92f32563a0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7f92ea91aee0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7f92f32563a0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7f92ea91aee0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function CachingFileManager.__del__ at 0x7f92f32563a0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 244, in __del__\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/file_manager.py\", line 222, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\nException ignored in: <function File.close at 0x7f92ea91aee0>\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py\", line 1200, in close\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py\", line 463, in close\nTypeError: bad operand type for unary ~: 'NoneType'\n",
  "history_begin_time" : 1687318848248,
  "history_end_time" : 1687318877846,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Failed"
},{
  "history_id" : "D5poheZLB3st",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-04\"),\n  )\n  print(\"found results: \", results)\n  return results\n\nds = get_dataset(search_ssh())\nsubset = ds[\"analysed_sst\"].sel(lat=slice(-90, 90), \n                                lon=slice(-180,180))\nplot_subset(subset)\n\n",
  "history_output" : "Traceback (most recent call last):\n  File \"/Users/joe/gw-workspace/D5poheZLB3st/retrieve_sst.py\", line 13, in <module>\n    ds = get_dataset(search_ssh())\nNameError: name 'search_ssh' is not defined\n",
  "history_begin_time" : 1687318835390,
  "history_end_time" : 1687318841692,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Failed"
},{
  "history_id" : "5lqwvos3wb6",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-04\"),\n  )\n  print(\"found results: \", results)\n  return results\n\n\nplot_subset(get_subset(get_dataset(search_and_get_sst()), \n                       \"analysed_sst\", \n                       lat=slice(-90, 90), \n                       lon=slice(-180,180)))\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 4\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-03T21:00:00.000Z', 'BeginningDateTime': '2021-07-02T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210703090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-04T21:00:00.000Z', 'BeginningDateTime': '2021-07-03T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210704090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 4 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 4/4 [00:00<00:00, 1651.46it/s]\nPROCESSING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nPROCESSING TASKS | :  25%|██▌       | 1/4 [00:00<00:02,  1.38it/s]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:01<00:00,  4.15it/s]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:01<00:00,  3.60it/s]\nCOLLECTING RESULTS | :   0%|          | 0/4 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 4/4 [00:00<00:00, 62601.55it/s]\n<xarray.Dataset>\nDimensions:           (time: 4, lat: 17999, lon: 36000)\nCoordinates:\n  * time              (time) datetime64[ns] 2021-07-01T09:00:00 ... 2021-07-0...\n  * lat               (lat) float32 -89.99 -89.98 -89.97 ... 89.97 89.98 89.99\n  * lon               (lon) float32 -180.0 -180.0 -180.0 ... 180.0 180.0 180.0\nData variables:\n    analysed_sst      (time, lat, lon) float32 dask.array<chunksize=(1, 17999, 36000), meta=np.ndarray>\n    analysis_error    (time, lat, lon) float32 dask.array<chunksize=(1, 17999, 36000), meta=np.ndarray>\n    mask              (time, lat, lon) float32 dask.array<chunksize=(1, 17999, 36000), meta=np.ndarray>\n    sea_ice_fraction  (time, lat, lon) float32 dask.array<chunksize=(1, 17999, 36000), meta=np.ndarray>\n    dt_1km_data       (time, lat, lon) timedelta64[ns] dask.array<chunksize=(1, 17999, 36000), meta=np.ndarray>\n    sst_anomaly       (time, lat, lon) float32 dask.array<chunksize=(1, 17999, 36000), meta=np.ndarray>\nAttributes: (12/47)\n    Conventions:                CF-1.7\n    title:                      Daily MUR SST, Final product\n    summary:                    A merged, multi-sensor L4 Foundation SST anal...\n    references:                 http://podaac.jpl.nasa.gov/Multi-scale_Ultra-...\n    institution:                Jet Propulsion Laboratory\n    history:                    created at nominal 4-day latency; replaced nr...\n    ...                         ...\n    project:                    NASA Making Earth Science Data Records for Us...\n    publisher_name:             GHRSST Project Office\n    publisher_url:              http://www.ghrsst.org\n    publisher_email:            ghrsst-po@nceo.ac.uk\n    processing_level:           L4\n    cdm_data_type:              grid\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/indexing.py\", line 72, in group_indexers_by_index\n    index = xindexes[key]\nKeyError: 'Latitude'\nDuring handling of the above exception, another exception occurred:\nTraceback (most recent call last):\n  File \"/Users/joe/gw-workspace/5lqwvos3wb6/retrieve_sst.py\", line 14, in <module>\n    plot_subset(get_subset(get_dataset(search_and_get_sst()), \n  File \"/Users/joe/gw-workspace/5lqwvos3wb6/earth_data_utils.py\", line 61, in get_subset\n    return ds[var_name].sel(Latitude=lat, Longitude=lon)\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/dataarray.py\", line 1332, in sel\n    ds = self._to_temp_dataset().sel(\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/dataset.py\", line 2504, in sel\n    pos_indexers, new_indexes = remap_label_indexers(\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/coordinates.py\", line 421, in remap_label_indexers\n    pos_indexers, new_indexes = indexing.remap_label_indexers(\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/indexing.py\", line 109, in remap_label_indexers\n    indexes, grouped_indexers = group_indexers_by_index(\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/indexing.py\", line 85, in group_indexers_by_index\n    raise KeyError(f\"{key} is not a valid dimension or coordinate\")\nKeyError: 'Latitude is not a valid dimension or coordinate'\n",
  "history_begin_time" : 1687318439859,
  "history_end_time" : 1687318467842,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : "100001",
  "indicator" : "Failed"
},{
  "history_id" : "XYWhBOUtZcPG",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-04\"),\n  )\n  print(\"found results: \", results)\n  return results\n\n\nplot_subset(get_subset(get_dataset(search_and_get_sst()), \n                       \"analysed_sst\", \n                       lat=slice(-90, 90), \n                       lon=slice(-180,180)))\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 4\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-03T21:00:00.000Z', 'BeginningDateTime': '2021-07-02T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210703090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-04T21:00:00.000Z', 'BeginningDateTime': '2021-07-03T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210704090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 4 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 4/4 [00:00<00:00, 549.37it/s]\nPROCESSING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nPROCESSING TASKS | :  25%|██▌       | 1/4 [00:01<00:03,  1.00s/it]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:01<00:00,  3.93it/s]\nCOLLECTING RESULTS | :   0%|          | 0/4 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 4/4 [00:00<00:00, 57260.12it/s]\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/indexing.py\", line 72, in group_indexers_by_index\n    index = xindexes[key]\nKeyError: 'Latitude'\nDuring handling of the above exception, another exception occurred:\nTraceback (most recent call last):\n  File \"/Users/joe/gw-workspace/XYWhBOUtZcPG/retrieve_sst.py\", line 14, in <module>\n    plot_subset(get_subset(get_dataset(search_and_get_sst()), \n  File \"/Users/joe/gw-workspace/XYWhBOUtZcPG/earth_data_utils.py\", line 60, in get_subset\n    return ds[var_name].sel(Latitude=lat, Longitude=lon)\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/dataarray.py\", line 1332, in sel\n    ds = self._to_temp_dataset().sel(\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/dataset.py\", line 2504, in sel\n    pos_indexers, new_indexes = remap_label_indexers(\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/coordinates.py\", line 421, in remap_label_indexers\n    pos_indexers, new_indexes = indexing.remap_label_indexers(\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/indexing.py\", line 109, in remap_label_indexers\n    indexes, grouped_indexers = group_indexers_by_index(\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/indexing.py\", line 85, in group_indexers_by_index\n    raise KeyError(f\"{key} is not a valid dimension or coordinate\")\nKeyError: 'Latitude is not a valid dimension or coordinate'\n",
  "history_begin_time" : 1687317902150,
  "history_end_time" : 1687317936884,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Failed"
},{
  "history_id" : "4NoU0dDwnwmb",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-04\"),\n  )\n  print(\"found results: \", results)\n  return results\n\n  \nplot_subset(get_subset(get_dataset(search_ssh()), \n                       \"analysed_sst\", \n                       lat=slice(-90, 90), \n                       lon=slice(-180,180)))\n\n",
  "history_output" : "Traceback (most recent call last):\n  File \"/Users/joe/gw-workspace/4NoU0dDwnwmb/retrieve_sst.py\", line 14, in <module>\n    plot_subset(get_subset(get_dataset(search_ssh()), \nNameError: name 'search_ssh' is not defined\n",
  "history_begin_time" : 1687317850798,
  "history_end_time" : 1687317857863,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Failed"
},{
  "history_id" : "4AheIx9gmzVw",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-04\"),\n  )\n  print(\"found results: \", results)\n  return results\n\n  \nplot_subset(get_subset(get_dataset(search_and_get_sst())))\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 4\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-03T21:00:00.000Z', 'BeginningDateTime': '2021-07-02T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210703090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-04T21:00:00.000Z', 'BeginningDateTime': '2021-07-03T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210704090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 4 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 4/4 [00:00<00:00, 1444.69it/s]\nPROCESSING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nPROCESSING TASKS | :  25%|██▌       | 1/4 [00:00<00:02,  1.17it/s]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:00<00:00,  5.27it/s]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:00<00:00,  4.17it/s]\nCOLLECTING RESULTS | :   0%|          | 0/4 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 4/4 [00:00<00:00, 27962.03it/s]\n<xarray.Dataset>\nDimensions:           (time: 4, lat: 17999, lon: 36000)\nCoordinates:\n  * time              (time) datetime64[ns] 2021-07-01T09:00:00 ... 2021-07-0...\n  * lat               (lat) float32 -89.99 -89.98 -89.97 ... 89.97 89.98 89.99\n  * lon               (lon) float32 -180.0 -180.0 -180.0 ... 180.0 180.0 180.0\nData variables:\n    analysed_sst      (time, lat, lon) float32 dask.array<chunksize=(1, 17999, 36000), meta=np.ndarray>\n    analysis_error    (time, lat, lon) float32 dask.array<chunksize=(1, 17999, 36000), meta=np.ndarray>\n    mask              (time, lat, lon) float32 dask.array<chunksize=(1, 17999, 36000), meta=np.ndarray>\n    sea_ice_fraction  (time, lat, lon) float32 dask.array<chunksize=(1, 17999, 36000), meta=np.ndarray>\n    dt_1km_data       (time, lat, lon) timedelta64[ns] dask.array<chunksize=(1, 17999, 36000), meta=np.ndarray>\n    sst_anomaly       (time, lat, lon) float32 dask.array<chunksize=(1, 17999, 36000), meta=np.ndarray>\nAttributes: (12/47)\n    Conventions:                CF-1.7\n    title:                      Daily MUR SST, Final product\n    summary:                    A merged, multi-sensor L4 Foundation SST anal...\n    references:                 http://podaac.jpl.nasa.gov/Multi-scale_Ultra-...\n    institution:                Jet Propulsion Laboratory\n    history:                    created at nominal 4-day latency; replaced nr...\n    ...                         ...\n    project:                    NASA Making Earth Science Data Records for Us...\n    publisher_name:             GHRSST Project Office\n    publisher_url:              http://www.ghrsst.org\n    publisher_email:            ghrsst-po@nceo.ac.uk\n    processing_level:           L4\n    cdm_data_type:              grid\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/dataset.py\", line 1395, in _construct_dataarray\n    variable = self._variables[name]\nKeyError: 'SLA'\nDuring handling of the above exception, another exception occurred:\nTraceback (most recent call last):\n  File \"/Users/joe/gw-workspace/4AheIx9gmzVw/retrieve_sst.py\", line 14, in <module>\n    plot_subset(get_subset(get_dataset(search_and_get_sst())))\n  File \"/Users/joe/gw-workspace/4AheIx9gmzVw/earth_data_utils.py\", line 61, in get_subset\n    return ds['SLA'].sel(Latitude=slice(10.8, 40.9), Longitude=slice(234.5,260.5))\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/dataset.py\", line 1499, in __getitem__\n    return self._construct_dataarray(key)\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/dataset.py\", line 1397, in _construct_dataarray\n    _, name, variable = _get_virtual_variable(\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/dataset.py\", line 170, in _get_virtual_variable\n    ref_var = variables[ref_name]\nKeyError: 'SLA'\n",
  "history_begin_time" : 1687317301301,
  "history_end_time" : 1687317333319,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Failed"
},{
  "history_id" : "GNDa18SBhJTV",
  "history_input" : "from earth_data_utils import *\n\ndef search_and_get_sst():\n  auth_earthaccess()\n  results = earthaccess.search_data(\n      short_name=sst_short_name,\n      cloud_hosted=True,\n      temporal=(\"2021-07-01\", \"2021-07-04\"),\n  )\n  print(\"found results: \", results)\n  return results\n\n  \nplot_subset(get_subset(get_dataset(search_and_get_sst())))\n\n",
  "history_output" : "You're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 08/19/2023\nUsing .netrc file for EDL\nGranules found: 4\nfound results:  [Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-01T21:00:00.000Z', 'BeginningDateTime': '2021-06-30T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210701090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-02T21:00:00.000Z', 'BeginningDateTime': '2021-07-01T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210702090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-03T21:00:00.000Z', 'BeginningDateTime': '2021-07-02T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210703090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc'], Collection: {'Version': '4.1', 'ShortName': 'MUR-JPL-L4-GLOB-v4.1'}\nSpatial coverage: {'HorizontalSpatialDomain': {'Geometry': {'BoundingRectangles': [{'WestBoundingCoordinate': -180, 'SouthBoundingCoordinate': -90, 'EastBoundingCoordinate': 180, 'NorthBoundingCoordinate': 90}]}}}\nTemporal coverage: {'RangeDateTime': {'EndingDateTime': '2021-07-04T21:00:00.000Z', 'BeginningDateTime': '2021-07-03T21:00:00.000Z'}}\nSize(MB): 0\nData: ['https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/MUR-JPL-L4-GLOB-v4.1/20210704090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1.nc']]\n Opening 4 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 4/4 [00:00<00:00, 1220.78it/s]\nPROCESSING TASKS | :   0%|          | 0/4 [00:00<?, ?it/s]\nPROCESSING TASKS | :  25%|██▌       | 1/4 [00:01<00:03,  1.00s/it]\nPROCESSING TASKS | : 100%|██████████| 4/4 [00:01<00:00,  3.99it/s]\nCOLLECTING RESULTS | :   0%|          | 0/4 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 4/4 [00:00<00:00, 28149.69it/s]\nTraceback (most recent call last):\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/dataset.py\", line 1395, in _construct_dataarray\n    variable = self._variables[name]\nKeyError: 'SLA'\nDuring handling of the above exception, another exception occurred:\nTraceback (most recent call last):\n  File \"/Users/joe/gw-workspace/GNDa18SBhJTV/retrieve_sst.py\", line 14, in <module>\n    plot_subset(get_subset(get_dataset(search_and_get_sst())))\n  File \"/Users/joe/gw-workspace/GNDa18SBhJTV/earth_data_utils.py\", line 60, in get_subset\n    return ds['SLA'].sel(Latitude=slice(15.8, 35.9), Longitude=slice(234.5,260.5))\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/dataset.py\", line 1499, in __getitem__\n    return self._construct_dataarray(key)\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/dataset.py\", line 1397, in _construct_dataarray\n    _, name, variable = _get_virtual_variable(\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/core/dataset.py\", line 170, in _get_virtual_variable\n    ref_var = variables[ref_name]\nKeyError: 'SLA'\n",
  "history_begin_time" : 1687317111951,
  "history_end_time" : 1687317147523,
  "history_notes" : null,
  "history_process" : "nlsntt",
  "host_id" : null,
  "indicator" : "Failed"
},]
