[{
  "history_id" : "arwtgpbpcys",
  "history_input" : "\n\n\n# Suppress warnings\nimport warnings\nwarnings.simplefilter('ignore')\nwarnings.filterwarnings('ignore')\n\n# Direct access\nimport earthaccess \nfrom pprint import pprint\nimport xarray as xr\n\n# Harmony\nimport geopandas as gpd\nimport geoviews as gv\ngv.extension('bokeh', 'matplotlib')\nfrom harmony import BBox, Client, Collection, Request, LinkType\nimport datetime as dt\nimport s3fs",
  "history_output" : "",
  "history_begin_time" : 1686762195610,
  "history_end_time" : 1686762202681,
  "history_notes" : null,
  "history_process" : "wttkvt",
  "host_id" : "100001",
  "indicator" : "Done"
},{
  "history_id" : "sgrwmws0csm",
  "history_input" : "from earth_data_utils import *\n\nssh_short_name = \"SEA_SURFACE_HEIGHT_ALT_GRIDS_L4_2SATS_5DAY_6THDEG_V_JPL2205\"\n\nresults = earthaccess.search_data(\n    short_name=ssh_short_name,\n    cloud_hosted=True,\n    temporal=(\"2021-07-01\", \"2021-09-30\"),\n)",
  "history_output" : "Granules found: 18\n",
  "history_begin_time" : 1686762203813,
  "history_end_time" : 1686762211441,
  "history_notes" : null,
  "history_process" : "yvo1ds",
  "host_id" : "100001",
  "indicator" : "Done"
},{
  "history_id" : "7fi74jfka0q",
  "history_input" : "from search_data import *\n\n\nssh_short_name = \"SEA_SURFACE_HEIGHT_ALT_GRIDS_L4_2SATS_5DAY_6THDEG_V_JPL2205\"\n\nresults = earthaccess.search_data(\n    short_name=ssh_short_name,\n    cloud_hosted=True,\n    temporal=(\"2021-07-01\", \"2021-09-30\"),\n)\nsst_short_name=\"MUR-JPL-L4-GLOB-v4.1\"\n\nresults = earthaccess.search_data(\n    short_name=ssh_short_name,\n    cloud_hosted=True,\n    temporal=(\"2021-07-01\", \"2021-09-30\"),\n)\n\nauth = earthaccess.login(strategy=\"netrc\", persist=True)\nds = xr.open_mfdataset(earthaccess.open(results))\ngeojson_path = '/home/jovyan/gulf.json'\ngdf = gpd.read_file(geojson_path) #Return a GeoDataFrame object\n\n\nharmony_client = Client()\nsst_short_name=\"MUR-JPL-L4-GLOB-v4.1\"\n\nrequest = Request(\n  collection=Collection(id=sst_short_name),\n  shape=geojson_path,\n  temporal={\n    'start': dt.datetime(2021, 8, 1, 1),\n    'stop': dt.datetime(2021, 8, 1, 2)   \n  },\n)\njob_id = harmony_client.submit(request)\nharmony_client.wait_for_processing(job_id, show_progress=False)\ndata = harmony_client.result_json(job_id)\nresults = harmony_client.result_urls(job_id, link_type=LinkType.s3)\nurls = list(results)\nurl = urls[0]\n",
  "history_output" : "Granules found: 18\nGranules found: 18\nGranules found: 18\nYou're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 07/30/2023\nUsing .netrc file for EDL\n Opening 18 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 18/18 [00:00<00:00, 1775.49it/s]\nPROCESSING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nPROCESSING TASKS | :   6%|▌         | 1/18 [00:00<00:12,  1.32it/s]\nPROCESSING TASKS | :  11%|█         | 2/18 [00:00<00:06,  2.53it/s]\nPROCESSING TASKS | :  33%|███▎      | 6/18 [00:01<00:01,  9.06it/s]\nPROCESSING TASKS | :  50%|█████     | 9/18 [00:01<00:01,  5.79it/s]\nPROCESSING TASKS | :  61%|██████    | 11/18 [00:01<00:00,  7.22it/s]\nPROCESSING TASKS | :  72%|███████▏  | 13/18 [00:01<00:00,  8.65it/s]\nPROCESSING TASKS | :  94%|█████████▍| 17/18 [00:02<00:00,  7.45it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00,  6.79it/s]\nCOLLECTING RESULTS | :   0%|          | 0/18 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 18/18 [00:00<00:00, 65707.11it/s]\nTraceback (most recent call last):\n  File \"/Users/joe/gw-workspace/7fi74jfka0q/earth_access_authenticate.py\", line 20, in <module>\n    ds = xr.open_mfdataset(earthaccess.open(results))\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/api.py\", line 908, in open_mfdataset\n    datasets = [open_(p, **open_kwargs) for p in paths]\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/api.py\", line 908, in <listcomp>\n    datasets = [open_(p, **open_kwargs) for p in paths]\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/api.py\", line 479, in open_dataset\n    engine = plugins.guess_engine(filename_or_obj)\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/plugins.py\", line 155, in guess_engine\n    raise ValueError(error_msg)\nValueError: found the following matches with the input file in xarray's IO backends: ['h5netcdf']. But their dependencies may not be installed, see:\nhttp://xarray.pydata.org/en/stable/user-guide/io.html \nhttp://xarray.pydata.org/en/stable/getting-started-guide/installing.html\n",
  "history_begin_time" : 1686762212738,
  "history_end_time" : 1686762229835,
  "history_notes" : null,
  "history_process" : "cgvhiy",
  "host_id" : "100001",
  "indicator" : "Failed"
},{
  "history_id" : "41gm8y19407",
  "history_input" : "# Suppress warnings\nimport os\nimport warnings\nwarnings.simplefilter('ignore')\nwarnings.filterwarnings('ignore')\n\n# Direct access\nimport earthaccess \nfrom pprint import pprint\nimport xarray as xr\n\n# Harmony\nimport geopandas as gpd\nimport geoviews as gv\ngv.extension('bokeh', 'matplotlib')\nfrom harmony import BBox, Client, Collection, Request, LinkType\nimport datetime as dt\nimport s3fs\nimport matplotlib.pyplot as plt\nfrom earth_access_authenticate import *\n\ncreds = harmony_client.aws_credentials()\ns3_fs = s3fs.S3FileSystem(\n  key=creds['aws_access_key_id'],\n  secret=creds['aws_secret_access_key'],\n  token=creds['aws_session_token'],\n  client_kwargs={'region_name':'us-west-2'},\n)\nf = s3_fs.open(url, mode='rb')\nds = xr.open_dataset(f)\nds.analysed_sst.plot()\nhome_dir = os.path.expanduser('~')\nplt.savefig(os.path.join(home_dir, 'plot2.png'))",
  "history_output" : "Granules found: 18\nGranules found: 18\nGranules found: 18\nYou're now authenticated with NASA Earthdata Login\nUsing token with expiration date: 07/30/2023\nUsing .netrc file for EDL\n Opening 18 granules, approx size: 0.0 GB\nQUEUEING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nQUEUEING TASKS | : 100%|██████████| 18/18 [00:00<00:00, 2177.92it/s]\nPROCESSING TASKS | :   0%|          | 0/18 [00:00<?, ?it/s]\nPROCESSING TASKS | :   6%|▌         | 1/18 [00:00<00:13,  1.26it/s]\nPROCESSING TASKS | :  28%|██▊       | 5/18 [00:01<00:02,  5.74it/s]\nPROCESSING TASKS | :  50%|█████     | 9/18 [00:01<00:01,  7.88it/s]\nPROCESSING TASKS | :  61%|██████    | 11/18 [00:01<00:00,  7.60it/s]\nPROCESSING TASKS | :  89%|████████▉ | 16/18 [00:01<00:00, 11.04it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00, 10.56it/s]\nPROCESSING TASKS | : 100%|██████████| 18/18 [00:02<00:00,  8.32it/s]\nCOLLECTING RESULTS | :   0%|          | 0/18 [00:00<?, ?it/s]\nCOLLECTING RESULTS | : 100%|██████████| 18/18 [00:00<00:00, 94254.02it/s]\nTraceback (most recent call last):\n  File \"/Users/joe/gw-workspace/41gm8y19407/s3_file_storage.py\", line 20, in <module>\n    from earth_access_authenticate import *\n  File \"/Users/joe/gw-workspace/41gm8y19407/earth_access_authenticate.py\", line 20, in <module>\n    ds = xr.open_mfdataset(earthaccess.open(results))\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/api.py\", line 908, in open_mfdataset\n    datasets = [open_(p, **open_kwargs) for p in paths]\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/api.py\", line 908, in <listcomp>\n    datasets = [open_(p, **open_kwargs) for p in paths]\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/api.py\", line 479, in open_dataset\n    engine = plugins.guess_engine(filename_or_obj)\n  File \"/Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages/xarray/backends/plugins.py\", line 155, in guess_engine\n    raise ValueError(error_msg)\nValueError: found the following matches with the input file in xarray's IO backends: ['h5netcdf']. But their dependencies may not be installed, see:\nhttp://xarray.pydata.org/en/stable/user-guide/io.html \nhttp://xarray.pydata.org/en/stable/getting-started-guide/installing.html\n",
  "history_begin_time" : 1686762231540,
  "history_end_time" : 1686762247028,
  "history_notes" : null,
  "history_process" : "1b4ko0",
  "host_id" : "100001",
  "indicator" : "Failed"
},{
  "history_id" : "naa8j6f067r",
  "history_input" : "#!/bin/bash\npip3 install geopandas earthaccess xarray harmony-py s3fs\n",
  "history_output" : "Requirement already satisfied: geopandas in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (0.10.2)\nRequirement already satisfied: earthaccess in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (0.5.2)\nRequirement already satisfied: xarray in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (0.20.2)\nRequirement already satisfied: harmony-py in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (0.4.9)\nRequirement already satisfied: s3fs in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (2022.1.0)\nRequirement already satisfied: pandas>=0.25.0 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from geopandas) (1.3.4)\nRequirement already satisfied: pyproj>=2.2.0 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from geopandas) (3.3.0)\nRequirement already satisfied: shapely>=1.6 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from geopandas) (1.8.1.post1)\nRequirement already satisfied: fiona>=1.8 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from geopandas) (1.8.20)\nRequirement already satisfied: pqdm>=0.1 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from earthaccess) (0.2.0)\nRequirement already satisfied: fsspec>=2022.1 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from earthaccess) (2022.1.0)\nRequirement already satisfied: tinynetrc<2.0.0,>=1.3.1 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from earthaccess) (1.3.1)\nRequirement already satisfied: python-cmr>=0.7 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from earthaccess) (0.7.0)\nRequirement already satisfied: multimethod>=1.8 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from earthaccess) (1.8)\nRequirement already satisfied: requests<3.0.0,>=2.26 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from earthaccess) (2.28.2)\nRequirement already satisfied: numpy>=1.18 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from xarray) (1.20.3)\nRequirement already satisfied: curlify~=2.2.1 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from harmony-py) (2.2.1)\nRequirement already satisfied: progressbar2~=3.55.0 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from harmony-py) (3.55.0)\nRequirement already satisfied: python-dotenv~=0.20.0 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from harmony-py) (0.20.0)\nRequirement already satisfied: python-dateutil~=2.8.2 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from harmony-py) (2.8.2)\nRequirement already satisfied: sphinxcontrib-napoleon~=0.7 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from harmony-py) (0.7)\nRequirement already satisfied: aiohttp<=4 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from s3fs) (3.8.1)\nRequirement already satisfied: aiobotocore~=2.1.0 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from s3fs) (2.1.0)\nRequirement already satisfied: botocore<1.23.25,>=1.23.24 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from aiobotocore~=2.1.0->s3fs) (1.23.24)\nRequirement already satisfied: wrapt>=1.10.10 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from aiobotocore~=2.1.0->s3fs) (1.12.1)\nRequirement already satisfied: aioitertools>=0.5.1 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from aiobotocore~=2.1.0->s3fs) (0.8.0)\nRequirement already satisfied: aiosignal>=1.1.2 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from aiohttp<=4->s3fs) (1.2.0)\nRequirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from aiohttp<=4->s3fs) (4.0.2)\nRequirement already satisfied: charset-normalizer<3.0,>=2.0 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from aiohttp<=4->s3fs) (2.0.10)\nRequirement already satisfied: multidict<7.0,>=4.5 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from aiohttp<=4->s3fs) (6.0.2)\nRequirement already satisfied: attrs>=17.3.0 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from aiohttp<=4->s3fs) (21.4.0)\nRequirement already satisfied: frozenlist>=1.1.1 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from aiohttp<=4->s3fs) (1.3.0)\nRequirement already satisfied: yarl<2.0,>=1.0 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from aiohttp<=4->s3fs) (1.7.2)\nRequirement already satisfied: jmespath<1.0.0,>=0.7.1 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from botocore<1.23.25,>=1.23.24->aiobotocore~=2.1.0->s3fs) (0.10.0)\nRequirement already satisfied: urllib3<1.27,>=1.25.4 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from botocore<1.23.25,>=1.23.24->aiobotocore~=2.1.0->s3fs) (1.26.8)\nRequirement already satisfied: munch in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8->geopandas) (2.5.0)\nRequirement already satisfied: click-plugins>=1.0 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8->geopandas) (1.1.1)\nRequirement already satisfied: click>=4.0 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8->geopandas) (8.0.4)\nRequirement already satisfied: six>=1.7 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8->geopandas) (1.16.0)\nRequirement already satisfied: setuptools in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8->geopandas) (67.6.0)\nRequirement already satisfied: cligj>=0.5 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8->geopandas) (0.7.2)\nRequirement already satisfied: certifi in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from fiona>=1.8->geopandas) (2021.10.8)\nRequirement already satisfied: pytz>=2017.3 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from pandas>=0.25.0->geopandas) (2021.3)\nRequirement already satisfied: typing-extensions in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from pqdm>=0.1->earthaccess) (4.1.1)\nRequirement already satisfied: bounded-pool-executor in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from pqdm>=0.1->earthaccess) (0.0.3)\nRequirement already satisfied: tqdm in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from pqdm>=0.1->earthaccess) (4.63.0)\nRequirement already satisfied: python-utils>=2.3.0 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from progressbar2~=3.55.0->harmony-py) (3.6.0)\nRequirement already satisfied: idna<4,>=2.5 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from requests<3.0.0,>=2.26->earthaccess) (3.3)\nRequirement already satisfied: pockets>=0.3 in /Users/l21-n02609-comm/opt/anaconda3/lib/python3.9/site-packages (from sphinxcontrib-napoleon~=0.7->harmony-py) (0.9.1)\n",
  "history_begin_time" : 1686762189422,
  "history_end_time" : 1686762193758,
  "history_notes" : null,
  "history_process" : "ru79i2",
  "host_id" : "100001",
  "indicator" : "Done"
}]
