[{
  "history_id" : "lr5j6k1e2h8",
  "history_input" : "\n\n\n# Suppress warnings\nimport warnings\nwarnings.simplefilter('ignore')\nwarnings.filterwarnings('ignore')\n\n# Direct access\nimport earthaccess \nfrom pprint import pprint\nimport xarray as xr\n\n# Harmony\nimport geopandas as gpd\nimport geoviews as gv\ngv.extension('bokeh', 'matplotlib')\nfrom harmony import BBox, Client, Collection, Request, LinkType\nimport datetime as dt\nimport s3fs",
  "history_output" : "Traceback (most recent call last):\n  File \"/Users/gokulprathin/gw-workspace/lr5j6k1e2h8/earth_data_utils.py\", line 10, in <module>\n    import earthaccess \nModuleNotFoundError: No module named 'earthaccess'\n",
  "history_begin_time" : 1686241482671,
  "history_end_time" : 1686241482803,
  "history_notes" : null,
  "history_process" : "wttkvt",
  "host_id" : "100001",
  "indicator" : "Failed"
},{
  "history_id" : "wdh8dwomdab",
  "history_input" : "from earth_data_utils import *\n\nssh_short_name = \"SEA_SURFACE_HEIGHT_ALT_GRIDS_L4_2SATS_5DAY_6THDEG_V_JPL2205\"\n\nresults = earthaccess.search_data(\n    short_name=ssh_short_name,\n    cloud_hosted=True,\n    temporal=(\"2021-07-01\", \"2021-09-30\"),\n)\n\nprint(results)",
  "history_output" : "Traceback (most recent call last):\n  File \"/Users/gokulprathin/gw-workspace/wdh8dwomdab/search_data.py\", line 1, in <module>\n    from earth_data_utils import *\n  File \"/Users/gokulprathin/gw-workspace/wdh8dwomdab/earth_data_utils.py\", line 10, in <module>\n    import earthaccess \nModuleNotFoundError: No module named 'earthaccess'\n",
  "history_begin_time" : 1686241484107,
  "history_end_time" : 1686241484240,
  "history_notes" : null,
  "history_process" : "yvo1ds",
  "host_id" : "100001",
  "indicator" : "Failed"
},{
  "history_id" : "php2ka87p54",
  "history_input" : "from search_data import *\n\nauth = earthaccess.login(strategy=\"netrc\", persist=True)\nds = xr.open_mfdataset(earthaccess.open(results))\nds_subset = ds['SLA'].sel(Latitude=slice(15.8, 35.9), Longitude=slice(234.5,260.5)) \ngdf = {\n  \"type\": \"FeatureCollection\",\n  \"features\": [\n    {\n      \"type\": \"Feature\",\n      \"properties\": {},\n      \"geometry\": {\n        \"type\": \"Polygon\",\n        \"coordinates\": [\n          [\n            [\n              -92.50277108026334,\n              29.56938225072281\n            ],\n            [\n              -97.13008502799451,\n              27.537299169977643\n            ],\n            [\n              -97.92333884760556,\n              23.117355263556085\n            ],\n            [\n              -96.20462223844827,\n              19.297357882373674\n            ],\n            [\n              -91.0484724109764,\n              19.2349555158823\n            ],\n            [\n              -89.32975580181909,\n              21.096419248573053\n            ],\n            [\n              -84.63633736912035,\n              21.404467339404434\n            ],\n            [\n              -80.9344862109354,\n              24.928609732834346\n            ],\n            [\n              -83.7769790645417,\n              30.199837703950273\n            ],\n            [\n              -92.50277108026334,\n              29.56938225072281\n            ]\n          ]\n        ]\n      }\n    }\n  ]\n}",
  "history_output" : "Traceback (most recent call last):\n  File \"/Users/gokulprathin/gw-workspace/php2ka87p54/earth_access_authenticate.py\", line 1, in <module>\n    from search_data import *\n  File \"/Users/gokulprathin/gw-workspace/php2ka87p54/search_data.py\", line 1, in <module>\n    from earth_data_utils import *\n  File \"/Users/gokulprathin/gw-workspace/php2ka87p54/earth_data_utils.py\", line 10, in <module>\n    import earthaccess \nModuleNotFoundError: No module named 'earthaccess'\n",
  "history_begin_time" : 1686241485832,
  "history_end_time" : 1686241485944,
  "history_notes" : null,
  "history_process" : "cgvhiy",
  "host_id" : "100001",
  "indicator" : "Failed"
},{
  "history_id" : "h768ikjba0m",
  "history_input" : "from earth_access_authenticate import *\n\nsst_short_name=\"MUR-JPL-L4-GLOB-v4.1\"\n\nrequest = Request(\n    collection=Collection(id=sst_short_name),\n    shape=geojson_path,\n    temporal={\n    'start': dt.datetime(2021, 8, 1, 1),\n    'stop': dt.datetime(2021, 8, 1, 2)   \n    },\n)\njob_id = harmony_client.submit(request)\nharmony_client.wait_for_processing(job_id, show_progress=True)\ndata = harmony_client.result_json(job_id)\nresults = harmony_client.result_urls(job_id, link_type=LinkType.s3)\nurls = list(results)\nurl = urls[0]",
  "history_output" : "Traceback (most recent call last):\n  File \"/Users/gokulprathin/gw-workspace/h768ikjba0m/connect_harmony_client.py\", line 1, in <module>\n    from earth_access_authenticate import *\n  File \"/Users/gokulprathin/gw-workspace/h768ikjba0m/earth_access_authenticate.py\", line 1, in <module>\n    from search_data import *\n  File \"/Users/gokulprathin/gw-workspace/h768ikjba0m/search_data.py\", line 1, in <module>\n    from earth_data_utils import *\n  File \"/Users/gokulprathin/gw-workspace/h768ikjba0m/earth_data_utils.py\", line 10, in <module>\n    import earthaccess \nModuleNotFoundError: No module named 'earthaccess'\n",
  "history_begin_time" : 1686241487261,
  "history_end_time" : 1686241487384,
  "history_notes" : null,
  "history_process" : "v2ow93",
  "host_id" : "100001",
  "indicator" : "Failed"
},{
  "history_id" : "4khylyjgoe4",
  "history_input" : "from connect_harmony_client import *\n\ncreds = harmony_client.aws_credentials()\ns3_fs = s3fs.S3FileSystem(\n    key=creds['aws_access_key_id'],\n    secret=creds['aws_secret_access_key'],\n    token=creds['aws_session_token'],\n    client_kwargs={'region_name':'us-west-2'},\n)\nf = s3_fs.open(url, mode='rb')\nds = xr.open_dataset(f)\nds.analysed_sst.plot();",
  "history_output" : "Traceback (most recent call last):\n  File \"/Users/gokulprathin/gw-workspace/4khylyjgoe4/s3_file_storage.py\", line 1, in <module>\n    from connect_harmony_client import *\n  File \"/Users/gokulprathin/gw-workspace/4khylyjgoe4/connect_harmony_client.py\", line 1, in <module>\n    from earth_access_authenticate import *\n  File \"/Users/gokulprathin/gw-workspace/4khylyjgoe4/earth_access_authenticate.py\", line 1, in <module>\n    from search_data import *\n  File \"/Users/gokulprathin/gw-workspace/4khylyjgoe4/search_data.py\", line 1, in <module>\n    from earth_data_utils import *\n  File \"/Users/gokulprathin/gw-workspace/4khylyjgoe4/earth_data_utils.py\", line 10, in <module>\n    import earthaccess \nModuleNotFoundError: No module named 'earthaccess'\n",
  "history_begin_time" : 1686241488968,
  "history_end_time" : 1686241489095,
  "history_notes" : null,
  "history_process" : "1b4ko0",
  "host_id" : "100001",
  "indicator" : "Failed"
}]
